import type { Product, SearchResponse } from "../domain";

function escapeHtml(value: string): string { return value.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;"); }
function card(product: Product, reason: string): string {
  const image = product.media.primaryImage ? '<img src="' + escapeHtml(product.media.primaryImage.url) + '" alt="' + escapeHtml(product.media.primaryImage.altText ?? product.name) + '" loading="lazy">' : '<div class="product-media-placeholder" aria-hidden="true">NOOR</div>';
  return '<article class="product-card"><a class="product-card-media" href="/products/' + encodeURIComponent(product.identity.id) + '" data-app-link>' + image + '</a><div class="product-card-body"><p class="eyebrow">' + escapeHtml(product.attributes.category === "optical" ? "عینک طبی" : "عینک آفتابی") + '</p><h2><a href="/products/' + encodeURIComponent(product.identity.id) + '" data-app-link>' + escapeHtml(product.name) + '</a></h2><p>' + escapeHtml(reason) + '</p><div class="product-card-actions"><a class="button button-secondary" href="/products/' + encodeURIComponent(product.identity.id) + '" data-app-link>جزئیات</a></div></div></article>';
}
export function renderSearch(routeView: HTMLElement, response: SearchResponse, products: readonly Product[]): void {
  const byId = new Map(products.map((product) => [product.identity.id, product]));
  const results = response.results.map((result) => { const product = byId.get(result.productId.id); return product ? card(product, result.reasons[0] ?? "بر اساس اطلاعات ساختاریافتهٔ فریم پیدا شد") : ""; }).join("");
  const query = response.query.text.trim();
  const empty = response.total === 0 && query ? '<section class="search-empty"><h2>نتیجه‌ای پیدا نشد</h2><p>عبارت را کوتاه‌تر کنید یا از واژه‌هایی مثل «طبی»، «آفتابی»، «مشکی»، «کلاسیک» یا فرم فریم استفاده کنید.</p><a class="button button-primary" href="/shopper?from=search" data-app-link>رفتن به مشاور انتخاب عینک</a></section>' : "";
  routeView.innerHTML = '<main class="search-page" id="main-content" aria-labelledby="search-title"><section class="search-intro"><p class="eyebrow">NOOR · SMART DISCOVERY</p><h1 id="search-title">جست‌وجوی فریم</h1><form class="search-form" data-search-form role="search"><label for="search-input">چه فریمی در ذهن دارید؟</label><div class="search-form-row"><input id="search-input" name="q" value="' + escapeHtml(query) + '" placeholder="مثلاً عینک طبی مشکی کلاسیک" autocomplete="off"><button class="button button-primary" type="submit">جست‌وجو</button></div></form><p class="search-meta">' + (response.total ? response.total + " نتیجه برای «" + escapeHtml(query) + "»" : query ? "بدون نتیجه" : "جست‌وجوی کنترل‌شده، بدون AI/LLM") + '</p>' + (query ? '<a class="search-shopper-handoff" href="/shopper?from=search&query=' + encodeURIComponent(query) + '" data-app-link>این انتخاب را با مشاور نور ادامه بده →</a>' : "") + '</section>' + empty + (results ? '<section class="search-results" aria-label="نتایج جست‌وجو"><div class="product-grid">' + results + "</div></section>" : "") + "</main>";
}
